---
- hosts: grande
  tasks:
   - name: Configure Grande
     nclu:
       commands:

         - add loopback lo ip address 192.168.255.1/32
         - add interface swp1 ip address 172.16.0.7/31
         - add ospf router-id 192.168.255.1
         - add ospf network 192.168.255.1/32 area 0.0.0.0
         - add ospf network 172.16.0.0/24 area 0.0.0.0

       commit: true

- hosts: spectrum
  tasks:
   - name: Configure Spectrum
     nclu:
       commands:

         - add loopback lo ip address 192.168.255.2/32
         - add interface swp1 ip address 172.16.0.9/31
         - add ospf router-id 192.168.255.2
         - add ospf network 192.168.255.2/32 area 0.0.0.0
         - add ospf network 172.16.0.0/24 area 0.0.0.0

       commit: true

- hosts: vpn01
  tasks:
   - name: Configure vpn01
     nclu:
       commands:

         - add loopback lo ip address 192.168.255.3/32
         - add interface swp1 ip address 172.16.0.3/31
         - add ospf router-id 172.16.0.3
         - add ospf network 192.168.255.3/32 area 0.0.0.0
         - add ospf network 172.16.0.0/24 area 0.0.0.0

       commit: true


- hosts: vpn02
  tasks:
   - name: Configure vpn02
     nclu:
       commands:

         - add loopback lo ip address 192.168.255.4/32
         - add interface swp1 ip address 172.16.0.5/31
         - add ospf router-id 192.168.255.4
         - add ospf network 192.168.255.4/32 area 0.0.0.0
         - add ospf network 172.16.0.0/24 area 0.0.0.0

       commit: true

- hosts: core01
  tasks:
   - name: Configure core01
     nclu:
       commands:

         - add loopback lo ip address 192.168.255.5/32
         - add interface swp3-4 ospf priority 100
         - add ospf router-id 192.168.255.5
         - add interface swp3 ip address 172.16.0.2/31
         - add interface swp4 ip address 172.16.0.6/31
         - add bond peerlink bond slaves swp1,swp2
         - add bond peerlink ip address 172.16.0.0/31
         - add ospf network 192.168.255.5/32 area 0.0.0.0
         - add ospf network 172.16.0.0/24 area 0.0.0.0
         - add bond peerlink ospf priority 100

       commit: true

- hosts: core02
  tasks:
   - name: Configure core02
     nclu:
       commands:

         - add loopback lo ip address 192.168.255.6/32
         - add interface swp3-4 ospf priority 90
         - add ospf router-id 192.168.255.6
         - add interface swp3 ip address 172.16.0.4/31
         - add interface swp4 ip address 172.16.0.8/31
         - add bond peerlink bond slaves swp1,swp2
         - add bond peerlink ip address 172.16.0.1/31
         - add ospf network 192.168.255.6/32 area 0.0.0.0
         - add ospf network 172.16.0.0/24 area 0.0.0.0
         - add bond peerlink ospf priority 90

       commit: true
